spring.application.name=GitGrok

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.model.embedding=ollama
spring.ai.ollama.chat.options.model=phi3:mini

# Pinecone Configuration
spring.ai.vectorstore.pinecone.apiKey=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=git-grok-index

#DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.vectorstore=DEBUG

github.token=${GITHUB_PAT}

# Give the CPU 2 minutes to process the context before timing out
spring.ai.ollama.chat.options.timeout=120s
# Force Ollama to stay in memory so it doesn't "cold start" next time
spring.ai.ollama.chat.options.keep-alive=24h
spring.ai.ollama.chat.options.temperature=0.0